"""Stage 7 initial schema."""
from alembic import op
import sqlalchemy as sa

revision = "0001_stage7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("workspaces", sa.Column("id", sa.String(32), primary_key=True), sa.Column("name", sa.String(120), nullable=False, unique=True), sa.Column("status", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("users", sa.Column("id", sa.String(32), primary_key=True), sa.Column("username", sa.String(120), nullable=False), sa.Column("password_hash", sa.String(200), nullable=False), sa.Column("role", sa.String(20), nullable=False), sa.Column("workspace_id", sa.String(32), sa.ForeignKey("workspaces.id")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.UniqueConstraint("username"))
    op.create_index("ix_users_username", "users", ["username"]); op.create_index("ix_users_workspace_id", "users", ["workspace_id"])
    op.create_table("agents", sa.Column("id", sa.String(32), primary_key=True), sa.Column("workspace_id", sa.String(32), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("agent_name", sa.String(120), nullable=False), sa.Column("machine_name", sa.String(200), nullable=False), sa.Column("client_version", sa.String(50), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("last_heartbeat", sa.DateTime(timezone=True)), sa.Column("profile_count", sa.Integer(), nullable=False), sa.Column("running_task_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("workspace_id", "machine_name", name="uq_agent_machine_workspace"))
    op.create_index("ix_agents_workspace_id", "agents", ["workspace_id"])
    op.create_table("profiles", sa.Column("id", sa.String(32), primary_key=True), sa.Column("workspace_id", sa.String(32), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("agent_id", sa.String(32), sa.ForeignKey("agents.id"), nullable=False), sa.Column("profile_id", sa.String(100), nullable=False), sa.Column("instance_id", sa.String(100), nullable=False), sa.Column("x_username", sa.String(30), nullable=False), sa.Column("x_account_id", sa.String(40), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.UniqueConstraint("agent_id", "profile_id", name="uq_agent_profile"))
    op.create_index("ix_profiles_workspace_id", "profiles", ["workspace_id"]); op.create_index("ix_profiles_agent_id", "profiles", ["agent_id"]); op.create_index("ix_profiles_profile_id", "profiles", ["profile_id"])
    op.create_table("accounts", sa.Column("id", sa.String(32), primary_key=True), sa.Column("workspace_id", sa.String(32), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("agent_id", sa.String(32), sa.ForeignKey("agents.id"), nullable=False), sa.Column("profile_id", sa.String(100), nullable=False), sa.Column("instance_id", sa.String(100), nullable=False), sa.Column("x_username", sa.String(30), nullable=False), sa.Column("x_account_id", sa.String(40), nullable=False), sa.Column("login_status", sa.String(30), nullable=False), sa.Column("browser_status", sa.String(30), nullable=False), sa.Column("account_status", sa.String(30), nullable=False), sa.Column("last_checked", sa.DateTime(timezone=True)), sa.Column("mapping_updated_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("agent_id", "profile_id", name="uq_account_agent_profile"))
    op.create_index("ix_accounts_workspace_id", "accounts", ["workspace_id"]); op.create_index("ix_accounts_agent_id", "accounts", ["agent_id"]); op.create_index("ix_accounts_profile_id", "accounts", ["profile_id"])
    op.create_table("tasks", sa.Column("id", sa.String(32), primary_key=True), sa.Column("workspace_id", sa.String(32), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("agent_id", sa.String(32), sa.ForeignKey("agents.id"), nullable=False), sa.Column("profile_id", sa.String(100), nullable=False), sa.Column("x_account_id", sa.String(40), nullable=False), sa.Column("task_type", sa.String(50), nullable=False), sa.Column("params", sa.JSON(), nullable=False), sa.Column("timeout", sa.Integer(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("pulled_at", sa.DateTime(timezone=True)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("duration", sa.Float(), nullable=False), sa.Column("result", sa.JSON()), sa.Column("error", sa.Text()))
    for name, cols in (("ix_tasks_workspace_id", ["workspace_id"]), ("ix_tasks_agent_id", ["agent_id"]), ("ix_tasks_profile_id", ["profile_id"]), ("ix_tasks_status", ["status"])): op.create_index(name, "tasks", cols)
    op.create_table("activities", sa.Column("id", sa.String(32), primary_key=True), sa.Column("workspace_id", sa.String(32), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("agent_id", sa.String(32), sa.ForeignKey("agents.id"), nullable=False), sa.Column("profile_id", sa.String(100), nullable=False), sa.Column("x_account_id", sa.String(40), nullable=False), sa.Column("task_id", sa.String(32), sa.ForeignKey("tasks.id"), nullable=False, unique=True), sa.Column("activity_type", sa.String(50), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("duration", sa.Float(), nullable=False), sa.Column("summary", sa.String(200), nullable=False), sa.Column("result", sa.JSON()), sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False))
    for name, cols in (("ix_activities_workspace_id", ["workspace_id"]), ("ix_activities_agent_id", ["agent_id"]), ("ix_activities_profile_id", ["profile_id"]), ("ix_activities_task_id", ["task_id"])): op.create_index(name, "activities", cols)


def downgrade():
    for table in ("activities", "tasks", "accounts", "profiles", "agents", "users", "workspaces"):
        op.drop_table(table)
