param(
    [string]$Output = "project-export\laogu-project-$(Get-Date -Format 'yyyyMMdd-HHmmss').md",
    [switch]$IncludeDeploymentDocs
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$project = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location -LiteralPath $project

$allowedExtensions = @(".py", ".ts", ".tsx", ".js", ".jsx", ".json", ".md", ".txt", ".ini", ".toml", ".yaml", ".yml", ".sh", ".ps1", ".css", ".html", ".sql", ".mako")
$excludedPath = @("agent_data/", "logs/", "dist/", "build/", "web/node_modules/", ".stage", ".venv/", "__pycache__/", ".pytest_cache/", "*.db", "*.sqlite", "*.sqlite3", "*.log", "*.key", "*.pem", "*.p12", "*.pfx", "credentials.json", "server.env", "backup.env")

function Is-Excluded([string]$path) {
    $normalized = $path.Replace("\\", "/")
    foreach ($rule in $excludedPath) {
        if ($rule.EndsWith("/")) {
            if ($normalized.StartsWith($rule, [StringComparison]::OrdinalIgnoreCase) -or $normalized.IndexOf("/$rule", [StringComparison]::OrdinalIgnoreCase) -ge 0) { return $true }
        } elseif ($rule.StartsWith("*")) {
            if ($normalized.EndsWith($rule.Substring(1), [StringComparison]::OrdinalIgnoreCase)) { return $true }
        } elseif ($normalized.Equals($rule, [StringComparison]::OrdinalIgnoreCase) -or $normalized.EndsWith("/$rule", [StringComparison]::OrdinalIgnoreCase)) { return $true }
    }
    return $false
}

function Redact-Secrets([string]$text) {
    $patterns = @(
        '(?im)^(\s*(?:[A-Z][A-Z0-9_]*(?:TOKEN|SECRET|PASSWORD|API_KEY|PRIVATE_KEY)[A-Z0-9_]*)\s*=\s*)[^#\r\n]+',
        '(?im)^(\s*(?:TELEGRAM_BOT_TOKEN|TELEGRAM_CHAT_ID|LAOGU_AI_CREDENTIAL_KEY)\s*=\s*)[^#\r\n]+',
        '(?i)(github_pat_[A-Za-z0-9_\-]{20,})',
        '(?i)(lag_[A-Za-z0-9_\-]{20,})'
    )
    foreach ($pattern in $patterns) { $text = [regex]::Replace($text, $pattern, '$1<REDACTED>') }
    return $text
}

$files = @(git ls-files | Where-Object {
    $path = $_
    if ([String]::IsNullOrWhiteSpace($path) -or (Is-Excluded $path)) { return $false }
    $extension = [IO.Path]::GetExtension($path).ToLowerInvariant()
    if ($extension -notin $allowedExtensions -and $path -notin @(".gitignore", ".gitattributes")) { return $false }
    if (-not $IncludeDeploymentDocs -and $path -like "deploy/ubuntu/*") { return $false }
    return $true
})

$outputPath = Join-Path $project $Output
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $outputPath) | Out-Null
$builder = [Text.StringBuilder]::new()
[void]$builder.AppendLine("# Laogu AI Agent project export")
[void]$builder.AppendLine()
[void]$builder.AppendLine("> Generated by scripts/export-project-markdown.ps1. Credentials, databases, logs, build output, and binaries are excluded.")
[void]$builder.AppendLine("> Generated at: $((Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'))")
[void]$builder.AppendLine("> File count: $($files.Count)")
[void]$builder.AppendLine()
[void]$builder.AppendLine("## Project structure")
[void]$builder.AppendLine()
[void]$builder.AppendLine('```text')
$files | ForEach-Object { [void]$builder.AppendLine($_) }
[void]$builder.AppendLine('```')

foreach ($file in $files) {
    $language = switch ([IO.Path]::GetExtension($file).ToLowerInvariant()) {
        ".py" { "python" }; ".ts" { "typescript" }; ".tsx" { "tsx" }; ".js" { "javascript" }; ".jsx" { "jsx" }
        ".ps1" { "powershell" }; ".sh" { "bash" }; ".json" { "json" }; ".css" { "css" }; ".sql" { "sql" }
        ".md" { "markdown" }; default { "text" }
    }
    [void]$builder.AppendLine()
    [void]$builder.AppendLine(('## `' + $file + '`'))
    [void]$builder.AppendLine()
    [void]$builder.AppendLine(('````' + $language))
    $content = [IO.File]::ReadAllText((Join-Path $project $file), [Text.Encoding]::UTF8)
    [void]$builder.AppendLine((Redact-Secrets $content).TrimEnd())
    [void]$builder.AppendLine('````')
}

[IO.File]::WriteAllText($outputPath, $builder.ToString(), [Text.UTF8Encoding]::new($false))
$hash = (Get-FileHash -LiteralPath $outputPath -Algorithm SHA256).Hash
Write-Host "EXPORT_OK=$outputPath"
Write-Host "FILES=$($files.Count)"
Write-Host "SHA256=$hash"
